controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

position_controller:
  ros__parameters:
    joints:
      - softleg_1_hip_joint
      - softleg_1_knee_joint

joint_state_broadcaster:
  ros__parameters:
    joints:
      - softleg_1_cart_joint
      - softleg_1_hip_joint
      - softleg_1_knee_joint
    use_sim_time: True
