controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    PD_control:
      type: rbt_pd_cnt/Rbt_PD_cnt
      
PD_control:
  ros__parameters:
    joint:
      - softleg_1_hip_joint
      - softleg_1_knee_joint
    K_d:
      - 6. # Nm/rad
      - 6.
      #- 5.  #doppio 5 est buono
      #- 5.0     
    K_p: 
      - 60.
      - 60.
      # - 20.0  # doppio 20 est buono
      #- 20.0
      # - 70.903527147
      # - 70.903527147
    init_pos:
      - -0.
      - -0.
    use_sim_time: True

joint_state_broadcaster:
  ros__parameters:
    joints:
      - softleg_1_cart_joint
      - softleg_1_hip_joint
      - softleg_1_knee_joint
    use_sim_time: True


    
    # interfaces:
    #   - position
    #   - velocity
    #   - effort
