controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz - Match Gazebo simulation rate ... I would it higher 

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    PD_control:
      type: rbt_pd_cnt/Rbt_PD_cnt
      
PD_control:
  ros__parameters:
    joint:
      - softleg_1_hip_joint
      - softleg_1_knee_joint
    K_d:
      - 3.0  # 30 is good
      - 0.17  # Restore damping for knee joint     
    K_p: 
      - 100.0  # 200 is good
      - 7.0
    init_pos:
      - 0.0
      - 0.0
    use_sim_time: True

joint_state_broadcaster:
  ros__parameters:
    joints:
      - softleg_1_cart_joint
      - softleg_1_hip_joint
      - softleg_1_knee_joint
    use_sim_time: True


    
    # interfaces:
    #   - position
    #   - velocity
    #   - effort
